spring:
  application:
    name: hello-spring-cloud-service-admin
  zipkin:
    base-url: http://127.0.0.1:9411

server:
  port: 8763

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
