spring:
  application:
    name: hello-spring-cloud-web-admin-ribbon
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  zipkin:
    base-url: http://127.0.0.1:9411

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
